### ISSUE TITLE
Local minikube tutorial failure

### ISSUE THREAD

**Issue by bgalvao** [datarevenue-berlin/OpenMLOps#94]
I am trying to follow the tutorial [Set up your local minikube machine learning architecture](https://github.com/datarevenue-berlin/OpenMLOps/blob/master/tutorials/set-up-minikube-cluster.md) for experimenting hands-on with the components of OpenMLOps. Unfortunately, I am not able to follow all the instructions to the end.

**Disclaimer: I am new to Terraform and Kubernetes.**

To begin with, I tried to start minikube in two ways,
1. with `minikube start --kubernetes-version=v1.17.17`
2. and without a specified kubernetes version.

In case 1., I could not get minikube to start running. [Here is the entire output of the command](https://gist.github.com/bgalvao/f21a51f341f6eb855326229e8980cc68).

In the latter (without specifying the version), I believe minikube defaults to v1.22.2 as per the output I get from `kubectl version`. In this case, I am able to get minikube running and start a tunnel as well:

```
Status:
        machine: minikube
        pid: 10105
        route: 10.96.0.0/12 -> 192.168.49.2
        minikube: Running
        services: [mlflow]
    errors: 
                minikube: no errors
                router: no errors
                loadbalancer emulator: no errors
```

All ok until I get to the step `terraform apply -var-file=my_vars.tfvars`, which outputs the following at the end (the only 3 changes not able to complete):

```
module.ambassador[0].helm_release.ambassador[0]: Creating...
module.dask-jupyterhub.helm_release.dask-jupyterhub: Creating...
module.prefect-server.helm_release.prefect-server: Creating...
╷
│ Error: failed to install CRD crds/filter.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
│ 
│   with module.ambassador[0].helm_release.ambassador[0],
│   on modules/ambassador/main.tf line 1, in resource "helm_release" "ambassador":
│    1: resource "helm_release" "ambassador" {
│ 
╵
╷
│ Error: failed to install CRD crds/daskclusters.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
│ 
│   with module.dask-jupyterhub.helm_release.dask-jupyterhub,
│   on modules/dask-jupyterhub/main.tf line 1, in resource "helm_release" "dask-jupyterhub":
│    1: resource "helm_release" "dask-jupyterhub" {
│ 
╵
╷
│ Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "RoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
│ 
│   with module.prefect-server.helm_release.prefect-server,
│   on modules/prefect-server/main.tf line 1, in resource "helm_release" "prefect-server":
│    1: resource "helm_release" "prefect-server" {
│ 
╵

```

Why is this happening?
